app.py
from flask import Flask
from database import db
from routes.participant import participant_bp
from routes.draw import draw_bp
from routes.exclusion import exclusion_bp
from routes.updateParticipant import updateParticipant_bp
from routes.login import login_bp

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///secretSanta.db'
db.init_app(app)

app.secret_key = 'une_clé_secrète_très_sécurisée'

app.register_blueprint(login_bp)
app.register_blueprint(participant_bp)
app.register_blueprint(draw_bp)
app.register_blueprint(exclusion_bp)
app.register_blueprint(updateParticipant_bp)

if __name__ == '__main__':
    app.run(debug=True)

routes/draw.py
from flask import Blueprint, render_template
from services.serviceDraw import draw
from database import Draw,Participant

draw_bp = Blueprint('tirage', __name__)

@draw_bp.route('/tirage')
def drawRoute():
    participants = Participant.query.all()
    error_message = None
    try:
        lastDraw = draw(participants)
    except ValueError as e:
        error_message = str(e)
    drawHistory = Draw.query.order_by(Draw.created.desc()).limit(5).all()
    return render_template('/tirage.html', draws=drawHistory, error=error_message)

routes/exclusion.py
from flask import Blueprint, redirect
from services.serviceParticipant import exclude_participant, include_participant

exclusion_bp = Blueprint('exclusion', __name__)

@exclusion_bp.route('/exclusion/<int:id>/<int:idToExclude>', methods=['POST'])
def exclude(id, idToExclude):
    exclude_participant(id, idToExclude)
    return redirect(f'/update/{id}')

@exclusion_bp.route('/inclusion/<int:id>/<int:idToInclude>', methods=['POST'])
def include(id, idToInclude):
    include_participant(id, idToInclude)
    return redirect(f'/update/{id}')

routes/login.py
from flask import Blueprint, request,session,flash,render_template,redirect,url_for
from database import db, Participant
from werkzeug.security import generate_password_hash, check_password_hash

login_bp = Blueprint('login', __name__)

@login_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        participant = Participant.query.filter_by(email=email).first()
        
        if participant and check_password_hash(participant.password_hash, password):
            session['participant_id'] = participant.id
            session['user'] = participant.name 
            flash('Login successful!', 'success')
            return redirect(url_for('participant.participant')) 
        else:
            flash('Login failed. Check your email and password.', 'danger')
    
    return render_template('login.html')

@login_bp.route('/logout')
def logout():
    session.pop('participant_id', None)
    session.pop('user', None)  # Remove the user variable from the session
    flash('You have been logged out.', 'success')
    return redirect(url_for('login.login'))


@login_bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        password = request.form.get('password')

        if not name or not email or not password:
            flash('All fields are required!', 'error')
            return redirect(url_for('login.register'))

        existing_user = Participant.query.filter_by(email=email).first()
        if existing_user:
            flash('Email already registered!', 'error')
            return redirect(url_for('login.register'))

        new_participant = Participant(name=name, email=email)
        new_participant.set_password(password)
        db.session.add(new_participant)
        db.session.commit()

        flash('Registration successful! You can now log in.', 'success')
        return redirect(url_for('login.login'))

    return render_template('register.html')

routes/participant.py
from flask import Blueprint, render_template, request, redirect, flash
from services.serviceParticipant import add_participant, delete_participant
from database import db, Participant 

participant_bp = Blueprint('participant', __name__)

@participant_bp.route('/')
@participant_bp.route('/participant', methods=['POST', 'GET'])
def participant():
    if request.method == 'POST':
        name_new_participant = request.form['name']
        email_new_participant = request.form['email']
        try:
            add_participant(name_new_participant, email_new_participant)
            flash("Participant added successfully!", "success")
        except ValueError as e:
            flash(str(e), "danger")
        return redirect('/participant')
    else:
        participants = Participant.query.all()
        return render_template('participants.html', participants=participants)

@participant_bp.route('/delete/<int:id>')
def supprimer(id):
    delete_participant(id)
    return redirect('/participant')

routes/updateParticipant.py
from flask import Blueprint, render_template, request, redirect, flash
from services.serviceParticipant import clear_exclusions, update_participant
from database import db, Participant 

updateParticipant_bp = Blueprint('update', __name__)

@updateParticipant_bp.route('/update/<int:id>', methods=['GET', 'POST'])
def update(id):
    if request.method == 'POST':
        try:
            update_participant(id, request.form['name'], request.form['email'])
        except ValueError as e:
            flash(str(e), "danger")
        return redirect('/participant')
    else:
        participant_update = Participant.query.get(id)
        groupe = Participant.query.all()
        exclusions = [e.excluded_id for e in participant_update.exclusions]
        return render_template('/update_participant.html', participant=participant_update, groupe=groupe, exclusions=exclusions)

@updateParticipant_bp.route('/clear/<int:id>', methods=['POST'])
def clearExclusions(id):
    clear_exclusions(id)
    return redirect(f'/update/{id}')

templates/base.html
<!doctype html>
<title>Secret Santa</title>
<body>
  <div>
      <form action="/participant" method="GET">
          <input type="submit" value="Accueil">
      </form>
  </div>

  <div>
      {% if session['user'] %}
          <span>Welcome, {{ session['user'] }}</span>
          <a href="{{ url_for('login.logout') }}">Logout</a>
      {% else %}
          <a href="{{ url_for('login.login') }}">Login</a>
      {% endif %}
  </div>

  <main>
        {% block content %}
        {% endblock %}
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }}" role="alert">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}

  </main>
</body>

templates/login.html
{% extends 'base.html' %}

{% block content %}
<body>
    <div class="login-container">
        <h2>Login</h2>
        <form action="{{ url_for('login.login') }}" method="POST">
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" id="email" name="email" required>
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required>
            </div>
            <button type="submit">Login</button>
        </form>
        <p>Don't have an account? <a href="{{ url_for('login.register') }}">Register here</a></p>
    </div>
</body>
{% endblock %}

templates/participants.html
{% extends 'base.html' %}

{% block content %}
<body>
    <h1>Liste des Participants</h1>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Nom</th>
                <th>Email</th>
                <th>Creation Date</th>
            </tr>
        </thead>
        <tbody>
            {% for participant in participants %}
            <tr>
                <td>{{ participant.id }}</td>
                <td>{{ participant.name }}</td>
                <td>{{ participant.email }}</td>
                <td>{{ participant.created.strftime('%d/%m/%Y %H:%M:%S') }}</td>
                <td>
                    <a href="/delete/{{participant.id}}">Delete</a>
                    <br>
                    <a href="/update/{{participant.id}}">Update</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <form action="/participant" method="POST">
        <input type="text" name="name" id="name" required placeholder="Enter name">
        <input type="email" name="email" id="email" required placeholder="Enter email">
        <input type="submit" value="Add participant">
    </form>
    <form action="/tirage" method="GET">
        <input type="submit" value="Draw Secret Santa">
    </form>
</body>
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block content %}
<body>
    <h1>Register</h1>
    <form method="POST" action="/register">
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" required>
        <br>
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required>
        <br>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>
        <br>
        <button type="submit">Register</button>
    </form>
</body>
{% endblock %}

templates/tirage.html
{% extends 'base.html' %}

{% block content %}
<div class="name">
    <h1>Draw History</h1>

    {% if error %}
    <div class="alert alert-danger">
        {{ error }}
    </div>
    {% endif %}

    {% for draw in draws %}
    <div><strong>Draw id {{ draw.id }}, created on {{ draw.created.strftime('%d/%m/%Y %H:%M:%S') }}</strong></div>
    <ul>
        {% for assign in draw.assignments %}
        <li>{{ assign.giver.name }} gives to {{ assign.receiver.name }}</li>
        {% endfor %}
    </ul>
    {% endfor %}
    
</div>
<form action="/tirage" method="GET">
    <input type="submit" value="Draw once again">
</form>
{% endblock %}

templates/update_participant.html
{% extends 'base.html' %}

{% block content %}
<div class="name">
    <h1 style="text-align: center">Update Participant</h1>

    <div class="form">
        <form action="/update/{{participant.id}}" method="POST">
            <input type="text" name="name" id="name" value="{{participant.name}}">
            <input type="email" name="email" id="email" value="{{participant.email}}">
            <input type="submit" value="Update">
        </form>
    </div>
</div>
<div class="exclusion">
    <h1 style="text-align: center">Exclusions for {{ participant.name }}</h1>
    {% for canBeExcluded in groupe %}
        {% if canBeExcluded != participant %}
        <div class="form">
            {% set alreadyExcluded = canBeExcluded.id in exclusions %}

            {% if alreadyExcluded %}
                <form action="/inclusion/{{participant.id}}/{{canBeExcluded.id}}" method="POST">
                    <input type="submit" value="Include {{ canBeExcluded.name }}">
                </form>
            {% else %}
                <form action="/exclusion/{{participant.id}}/{{canBeExcluded.id}}" method="POST">
                    <input type="submit" value="Exclure {{ canBeExcluded.name }}">
                </form>
            {% endif %}
        </div>
        {% endif %}
    {% endfor %}
    <form action="/clear/{{participant.id}}" method="POST">
        <input type="submit" value="Clear all Exclusions">
    </form>
</div>
{% endblock %}